import { useAccounts } from '@/hooks/useAccounts';
import { useConnected } from '@/hooks/useConnected';
import { usePersona } from '@/hooks/usePersona';
import { Typography } from '@mui/material';
import Head from 'next/head'
import { Fragment } from 'react';



export default function Home() {
    
    const accounts = useAccounts();
    const persona = usePersona();
    const connected = useConnected();


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Typography> Persona: {persona?.label}</Typography>
                <Typography>Accounts Count: {accounts?.length}</Typography>
                {accounts?.map((item, index) => {
                    return (
                        <Fragment key={index + 1}>
                            <Typography>{index + 1}. {item.label}</Typography>
                        </Fragment>
                    )
                })}
                <Typography> Connected status: {connected.toString().toUpperCase()}</Typography>
            </>
        </>
    )
}
