/* tslint:disable */
/* eslint-disable */
/**
 * Babylon PTE API
 * Babylon Public Test Environment (PTE) API specification.
 *
 * The version of the OpenAPI document: 0.1.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComponentBlueprint
 */
export interface ComponentBlueprint {
    /**
     * 
     * @type {string}
     * @memberof ComponentBlueprint
     */
    packageAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentBlueprint
     */
    blueprintName: string;
}

export function ComponentBlueprintFromJSON(json: any): ComponentBlueprint {
    return ComponentBlueprintFromJSONTyped(json, false);
}

export function ComponentBlueprintFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentBlueprint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'packageAddress': json['package_address'],
        'blueprintName': json['blueprint_name'],
    };
}

export function ComponentBlueprintToJSON(value?: ComponentBlueprint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'package_address': value.packageAddress,
        'blueprint_name': value.blueprintName,
    };
}

