<!--suppress TypeScriptUnresolvedVariable -->
<script lang="ts">
    import Accordion, {Content, Header, Panel} from '@smui-extra/accordion';

    // noinspection ES6UnusedImports
    // Without this import the radix-connect-button is not available!
    import rdt from "../../lib/radixDappToolkit";
</script>

<div class="content-container">
    <span class="page-heading">About This Demo</span>

    <div style="width: 50vw; padding: 1rem">
        <div class="welcome-message mdc-typography--body1">
            Welcome to the demo frontend for the FlashyFi blueprint
        </div>
    </div>

    <Accordion style="width: 50vw" multiple>
        <Panel>
            <Header>FAQ #1: What is FlashyFi and what can I do with it?</Header>
            <Content>
                FlashyFi allows users to lend their tokens and NFTs to others for a fee, without having to
                transfer ownership. Unlike traditional flash loan applications, your tokens remain in your account
                throughout the process, allowing you to use, transfer, or sell them at any time without the need to
                withdraw them from some liquidity pool first.<br>
                <br>
                As a user you can either provide liquidity and earn yield or you can take out flash loans for a
                small fee.
            </Content>
        </Panel>
        <Panel>
            <Header>FAQ #2: How can I provide liquidity and earn yield?</Header>
            <Content>
                To provide liquidity, connect your wallet, go to "Manage Accounts," and configure which tokens you want
                to lend to other users. Please make sure to only lend tokens and NFTs that cannot be used to
                impersonate you. Lending tokens such as XRD is generally safe, but you should not lend something like a
                KYC badge.<br>
                <br>
                Each time a user takes out a flash loan from your account, they will have to pay you a small fee.
            </Content>
        </Panel>
        <Panel>
            <Header>FAQ #3: How can I borrow tokens or NFTs</Header>
            <Content>
                To take out a flash loan, go to the application's homepage and select the token you want to borrow,
                along with the desired amount and one of your accounts. You can then generate a Radix transaction
                manifest that performs the following four steps:

                <ol>
                    <li>Borrow tokens from other users who have enabled flash loans for their accounts.</li>
                    <li>
                        Take advantage of something like an arbitrage opportunity. In the generated manifest, this is
                        simulated by calling a faucet component.
                    </li>
                    <li>Return the borrowed tokens along with a fee.</li>
                    <li>Deposit any profits into your own account.</li>
                </ol>
                You can execute that manifest and it should generally work. However, please note that this is not
                representative of a typical use case. It is much more likely that flash loans are used by bots seeking
                to borrow liquidity to take advantage of arbitrage opportunities. This would then be a fully autonomous
                process, and the manifest would be generated by the bot or via a backend API.
            </Content>
        </Panel>
        <Panel>
            <Header>FAQ #4: Are there any limitations to this demo?</Header>
            <Content>
                Yes, there are several limitations to this demo:
                <ul>
                    <li>
                        <b>This demo is a pure frontend application:</b> it operates without any backend aside from the
                        Radix network itself. All data is queried directly from the Radix public gateway. If flash loans
                        are enabled for too many accounts, application performance might degrade. Please note that a
                        backend is avoided to keep the complexity of the demo to a minimum. If it were to be developed
                        into a real product, it would make much more sense to deploy a backend API along with the
                        frontend.
                    </li>
                    <li>
                        <b>You can only set fixed fees for all tokens:</b> the FlashyFi blueprint, which is deployed on
                        the Radix network, would allow you to specify a percentage fee for every fungible token that you
                        lend. However, this feature is disabled in this demo to ensure proper functionality. An XRD
                        faucet is used to simulate profiting from an arbitrage opportunity, and these XRDs are used to
                        pay any fees. If percentage fees were allowed, the transaction would always fail for non-XRD
                        tokens.
                    </li>
                    <li>
                        <b>You can only borrow fungible tokens:</b> As with the previous point, the FlashyFi blueprint
                        allows you to borrow both fungible tokens and NFTs. However, as this is a pure frontend
                        application, fetching all available NFT IDs for all accounts that are configured to lend that
                        NFT collection would be too computationally burdensome on the public gateway.
                    </li>
                    <li>
                        <b>You can only register account components:</b> The FlashyFi component utilized in this demo is
                        specifically set up to permit registration of normal accounts only. However, the blueprint
                        provides the flexibility to be instantiated such that it can also accept normal (non-account)
                        components as lenders as well. This functionality would enable users to integrate components
                        holding significant liquidity, such as AMM-style DEXs, giving them a secondary purpose.
                    </li>
                    <li>
                        <b>This demo <i>might</i> mess up your account's access rules:</b> When you flashyfi your
                        account, its access rules will be set to allow access to the <i>withdraw_by_amount</i> and
                        <i>withdraw_by_ids</i> methods by both your private key and by a special badge held securely in
                        the FlashyFi component. This works flawlessly as long as you have not modified the account's
                        access rules yourself. If you have, your changes will be overwritten.<br>
                        This problem only exists because I didn't have the time to do it properly. It is by no means
                        a general limitation of the Radix network.
                    </li>
                </ul>
            </Content>
        </Panel>
    </Accordion>
</div>

<style>
    .welcome-message {
        margin-top: 1rem;
        color: var(--mdc-theme-on-surface);
        background-color: var(--mdc-theme-surface);
        border: 1px solid var(--mdc-theme-surface);
        border-radius: 4px;
        padding: 1rem;
        text-align: center;
    }
</style>
